name: Docker CI Workflow
on:
  push:
    branches:
      - release
      - hotfix
      - develop
      - feature/*
      - bugfix/*      
    tags:
      - '**'

jobs:
  call-docker-ci-workflow:
    if: github.event_name == 'push'
    uses: netcracker/qubership-apihub-ci/.github/workflows/docker-ci.yml@main
    with:
      name: qubership-apihub-nodejs-dev-image
      file: development-environment/Dockerfile
      context: 'development-environment'
      platforms: linux/amd64
      labels: |
        maintainer=qubership